services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: messageexchange
      POSTGRES_PASSWORD: root1234
      POSTGRES_DB: messagedb
    ports:
    - "5432:5432" 

  client:
    image: client
    ports:
      - "5001:3000"
    environment:
      - NODE_ENV=production
      - WDS_SOCKET_PORT=0
      - API_URL=http://messageexchange:8080
    build:
      context: ./web-client
      dockerfile: Dockerfile

  messageexchange:
    image: ${DOCKER_REGISTRY-}messageexchange
    build:
      context: .
      dockerfile: MessageExchange/Dockerfile
    environment: 
      stringConnectDb: "Host=db;Database=messagedb;Username=messageexchange;Password=root1234"
    ports:
    - "8080:8080" 

  proxy:
    image: nginx:mainline
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

